# Generated by Django 3.2.9 on 2022-03-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32, verbose_name='IP')),
                ('port', models.CharField(max_length=32, verbose_name='端口')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '主机表',
            },
        ),
    ]
