# Generated by Django 3.2.9 on 2022-03-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('path', models.CharField(max_length=32, verbose_name='路径')),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '脚本表',
            },
        ),
    ]
