# Generated by Django 3.2.9 on 2022-03-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shells',
            name='path',
            field=models.FileField(upload_to='shellfile/', verbose_name='shell脚本'),
        ),
    ]
